site_name: 数字电路教程
site_author: USTC Vlab
site_url: https://vlab.ustc.edu.cn/guide/
repo_name: USTC-vlab/guide
use_directory_urls: false

theme:
  name: material
  language: zh

extra:
  analytics:
    provider: google
    property: UA-115907213-3
